package com.example.tlismimoti .order.model.modelOrderDet

data class Term(
    val affil_id: Any,
    val answer1: Any,
    val answer2: Any,
    val answer3: Any,
    val answer4: Any,
    val answer5: Any,
    val created_at: String,
    val featured: Int,
    val id: Int,
    val is_admin: Int,
    val prvideo: Any,
    val question1: Any,
    val question2: Any,
    val question3: Any,
    val question4: Any,
    val question5: Any,
    val service_location: Any,
    val service_type: Any,
    val slug: String,
    val status: Int,
    val title: String,
    val type: String,
    val updated_at: String,
    val user_id: Int,
    val youtube_link: Any
)